### PR TITLE
Quick question : Option queryAttributes - ambiguous column name #48 - additional flexibility for easier inheritance

### PR DESCRIPTION
**Pull request by robbykrlos**
- changed accessors for a more flexible inheritance on Options service (I just realized that even though I made my initial contribution on how the class was instantiated (https://github.com/laravel-enso/select/pull/49) I will make much more sense to open up the class for inheritance, and just inherit Options service + bind and override just the method I want to customize, then to copy the whole class + bind)

### CODE REVIEW

**Comment by robbykrlos** [comment]
Was this forgotten? If I can do something to make this PR better, let me know.

**Comment by aocneanu** [comment]
Hi @robbykrlos,

I looked over this a few times and I don't feel it's a good direction for us.

Imagine extrapolating this architecture all across Enso - make all internal logic open for modification from the exterior. And having built applications where tens of services would be customized like that. Whenever we would move a package forward, by adding/improving/refactoring (previously) internal functionalities, we would have to create major releases, because any change would be breaking. We would have all packages at version 1xx.x.x in one year, and the volume of work to correlate all versions across packages would be outstanding.

Also, it's very simple to create a custom trait/service, for your specific case and use it in your controller.
Or you could use a db view where the data would be prepared to work with the current builder (we never use views in our apps, I do not encourage anybody to do so, but the same stands for using groupBy in a selector or table)

**Comment by robbykrlos** [comment]
@aocneanu, ok, understood. We'll try to manage it another way. Thanks for your suggestions and for the time you took to think about all the implications. Much appreciated.

**Comment by robbykrlos** [comment]
http://phpsadness.com/sad/33 - funny how I came across this one, soon after our discussion

**Pull request closed without merging**
