### PR TITLE
add test 

### PR DESCRIPTION
**Pull request by raftx24**
add tests with 99% coverage
laravel-enso/select#18

### CODE REVIEW

**Review by raftx24 — COMMENTED** [review]
thanks a lot for reading my codes and improving it.
I read your changes with accuracy, and I will try to adhere to them in the future.

**Comment by aocneanu** [comment]
The tests still miss something. This package is Enso independent, so in order to test it outside it we should not rely on existing framework structures.In the Test class we should add two models and migrations and use them for testing the package (something similar to [this](https://github.com/laravel-enso/rememberable/blob/master/tests/features/RememberableTest.php))

**Comment by raftx24** [comment]
great, I will fix them

**Comment by aocneanu** [comment]
Looks good. The test is now 100 times faster also, not relying on Enso's migrations

**Pull request merged**
